### ISSUE TITLE
Add additional prop to button to change icon color on hover

### ISSUE THREAD

**Issue by anshumanv** [clarisights/KnitUI#52]
cc @arorayash @Kushagra8888

**Comment by Kushagra8888** [comment]
@arorayash If this is a very common use case, we can add a prop, otherwise I think it might be better to manipulate it through `className` or `style`

**Comment by arorayash** [comment]
Right now, it's not common. I guess for time being, using className makes total sense. Do we expose the class names? @Kushagra8888

**Comment by Kushagra8888** [comment]
@arorayash Yes, we expose `xlassName` and `style` props

**Comment by Kushagra8888** [comment]
@anshumanv can you try that?

**Comment by anshumanv** [comment]
What would be the best way to control the button icon's fill color? Can we inject custom styles to button icon somehow?

**Comment by Kushagra8888** [comment]
@anshumanv We will have to target the `path` within the `svg` (which is the icon) inside the button, and apply the `fill` property with the `:hover` pseudo-selector

**Comment by arorayash** [comment]
> target the `path` within the `svg` (which is the icon) 
Just a note, targeting the SVG alone(instead of path) should do too. The fill gets applied to the children.
