### ISSUE TITLE
Support onFocus & onBlur in Input props

### ISSUE THREAD

**Issue by anshumanv** [clarisights/KnitUI#84]
Presently Input doesn't pass onFocus and onBlur to the input tag, need it for several use cases.

cc @arorayash opting for a normal input tag for now. Will replace by KnitUI Input once this goes through. 

... But I need addonBefore though :(

**Comment by Kushagra8888** [comment]
@anshumanv Its already supported in the current master branch. The next release should address that,  will be releasing in a moment.

**Comment by anshumanv** [comment]
Ahh great, thanks @Kushagra8888 🙇 🙏
